import './globals.css';
import Navigation from './components/navigation';
import Footer from './components/footer';

export const metadata = {
  title: 'Mike B. Kaufmann',
  description: 'Generated by Next.js',
  icons: {
    icon: ['/favicon/favicon.ico?v=4'],
    apple: ['/favicon/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon/apple-touch-icon.png'],
  },
  manifest: '/favicon/site.webmanifest',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <Navigation /> 
        <main className="max-w-screen-xl justify-center">{children}</main>
        <Footer /> 
      </body>
    </html>
  );
}
