import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css';
import Footer from './components/footer';

export const metadata = {
  title: 'Mike B. Kaufmann',
  description: 'Generated by Next.js',
  icons: {
    icon: ['/favicon/favicon.ico?v=4'],
    apple: ['/favicon/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon/apple-touch-icon.png'],
  },
  manifest: '/favicon/site.webmanifest',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className="text-black bg-white dark:text-white dark:bg-black">
      <body className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">{children}</main>
        <Footer />
        <SpeedInsights/>
      </body>
    </html>
  );
}